use_frameworks!

target 'ComfirmMangerTest_Example' do
  pod 'ComfirmMangerTest', :path => '../'

  target 'ComfirmMangerTest_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
